name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Images
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04-arm]
        include:
          - platform: ubuntu-latest
            arch: amd64
          - platform: ubuntu-22.04-arm
            arch: arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/mediascanner
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short

      - name: Build and push single-platform image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/mediascanner:${{ matrix.arch }}-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  merge-manifests:
    name: Merge Multi-Arch Manifests
    needs: build-and-push
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/mediascanner
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short

      - name: Create and push manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/mediascanner:latest \
            ghcr.io/${{ github.repository_owner }}/mediascanner:amd64-${{ github.sha }} \
            ghcr.io/${{ github.repository_owner }}/mediascanner:arm64-${{ github.sha }}

          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' '); do
            docker manifest create $tag \
              ghcr.io/${{ github.repository_owner }}/mediascanner:amd64-${{ github.sha }} \
              ghcr.io/${{ github.repository_owner }}/mediascanner:arm64-${{ github.sha }}

            docker manifest push $tag
          done

          docker manifest push ghcr.io/${{ github.repository_owner }}/mediascanner:latest
